### PR TITLE
fix: link in readme

### PR DESCRIPTION
**Pull request by fgiering**

### CODE REVIEW

**Review by fgiering — COMMENTED** [review]
link was 404

**Review by nabinhait — APPROVED** [review]

**Comment by seliger** [comment]
The suggested link (below) is useless. It's like the non_profit section does not exist in the documentation.

https://docs.erpnext.com/docs/v14/user/manual/en/non_profit/introduction

**Comment by fgiering** [comment]
> The suggested link (below) is useless. It's like the non_profit section does not exist in the documentation.
> 
> https://docs.erpnext.com/docs/v14/user/manual/en/non_profit/introduction
> 

Thats right! Its been a year now. Where is the documentation available now?

**Comment by seliger** [comment]
The best I can find is this:

https://discuss.frappe.io/t/anyone-maintaining-this-product/103642/5

While it's not actively maintained, some folks (myself included) find value in such a module. Can the old documentation be put somewhere to be read and reviewed?

**Pull request merged**
